### PR TITLE
Recursive Operation Fixes

### PR DESCRIPTION
**Pull request by yushan87**
Recursive operations have been broken for a while. This pull request addresses the following problems:

1. Changed the grammar to force recursive procedures to supply a decreasing clause (Fix for #221) 
2. Make sure that all non-recursive procedures don't have a call to itself.
3. `FacilityOperationDec` contains an `OperationDec`. All old accessor methods are simply wrappers to  `OperationDec` methods.
4. Changes in `Populator` to address issues caused by 3.

### CODE REVIEW

**Comment by yushan87** [comment]
@dtwelch What are your thoughts on my changes?

**Comment by dtwelch** [comment]
https://github.com/dtwelch/resolve-lite/blob/de7eee42705524804e39682d1684215305b76623/compiler/src/edu/clemson/resolve/analysis/SanityCheckingListener.java

there's an old sanity check that I did for that awhile back in danland (its not currently on master though, so use above link to see); note the `CallCheckingListener` in the above should really have been a visitor (for efficiency reasons); but was too lazy.

several things to keep in mind:
1. op *isn't* labeled recursive -> so there should be no calls made it itself (if it does: then error and moveon) 
2. op *is* labeled recursive, but doesn't call itself -> error
3. (1 and 2 above) should also make sure decreasing clause is present (or absent--depending on the case)
4. if a program param expr shares in the statement list shares the same name as the operation your checking, it still doesn't necessarily mean its recursive... for instance it could be qualified... qualified.
5. None  of these take into considering mutual recursion messiness which I don't even thing we should account for in the language.

**Comment by dtwelch** [comment]
in other words, if it checks those things i think its ok

**Comment by yushan87** [comment]
So...

1. If a non-recursive op calls itself, then the populator would detect it and throw an error. You did it with another listener, I simply used the existing methods.
2. I agree the code is wrong, but is it an error that the compiler would need to throw? The VC generator would generate a termination VC that is not provable. If somehow it is provable without a recursive call, my guess is that your specification(s) is completely bogus.
3. The current syntax is to put the `Recursive` keyword in front of `Procedure`. I kept it that way for `FacilityOperationDec`. The parser stops people from putting `decreasing` clauses when it is not a recursive procedure.
4. For this case, I am depending on the symbol table returning the right `OperationEntry` and the `equals` method for `OperationEntry`. Hampton stores the current `OperationEntry` when visiting any `ProcedureDec` and I have extended it to do the same for `FacilityOperationDec`. When querying for the `OperationEntry` for the `CallStmt` (or `ProgramParamExp`), the only time we end up with the same `OperationEntry` is when they are the same. The symbol table would have thrown an error if there were duplicates or ambiguity in the calling statement.
5. I don't think this is possible in the old grammar. There is no way for you to define a recursive procedure and make a calling statement to another procedure that is yet to be seen. The symbol table would crash when querying for the `OperationEntry`. I don't know if we want to support mutual recursion. How often do these come up? 

Hopefully this makes everything clear. This works for the few things I have tested and will test it against all working files.

**Comment by dtwelch** [comment]
yeah, sounds good--didn't realize there was an equals for `OperationEntry`, interesting.

Anyways, with 2 I guess it wont prove so thats good enough. And an error does seem kinda harsh: maybe they hadn't gotten around to filling in the impl for the procedure yet, etc. Maybe a warning would be better, dunno.

**Comment by yushan87** [comment]
There isn't one. I am basically using `Object`'s default implementation for `equals` method. In other words, the two objects must refer to the same object. In this case it works, because we can't have duplicated symbols in our symbol table.

I agree that an warning would be good.

**Comment by yushan87** [comment]
Added a skeleton continuous integration testing for RESOLVE. More tests will need to be added at a future date.

**Pull request merged**
